version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
      timezone: 'Etc/UTC'
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
      timezone: 'Etc/UTC'
